org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[1,)

mod_id=applied_ammo_box
mod_name=Applied Ammo Box
mod_license=GNU GPL 3.0
mod_version=1.21.1-1.2.3-hotfix1
mod_group_id=com.nanaios.applied_ammo_box
mod_credits=Created by nanaios. Ported to 1.21.1 by Bomb787.
mod_authors=nanaios
mod_description=Adds a wireless ammo box for TACZ that pulls bullets from an ME network.

tacz_version=N9ffXNy0
ae2_version=19.2.17
ae_infinity_booster_version=FkjLiVaY
curios_ammo_version=lJXyeGdQ
guideme_version=bFr2FBaJ
tag_tooltips_version=6gXB1Kcv
curios_version=9.5.1+1.21.1
jei_version=19.27.0.340